# Code for POD Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootdeployment
spec:
  selector:
    matchLabels:
      app: spring
  replicas: 2
  template:
    metadata:
      name: springbootmongopod
      labels:
        app: spring
    spec:
      containers:
      - name: springbootcontainer
        image: mlvvprasad/spring-boot-mongo
        ports:
        - port: 8080
          containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongosvc
        - name: MONGO_DB_USERNAME
          value: vara
        - name: MONGO_DB_PASSWORD
          value: vara@123
---
# Code for service for spring POD

apiVersion: v1
kind: Service
metadata:
  name: springbootsvc
spec:
  type: NodePort
  selector:
    app: spring
  port:
  - port: 80
    targetPort: 8080
---
# Code for Mongo Db Pod

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodbrs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongodbpod
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodbcontainer
        image: mongo
        port:
        - port: 27017
          containerPort: 27017
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: vara
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: vara@123
---
# Code for Service for Mongo Db

apiVersion: vi
kind: Service
metadata:
  name: mongosvc
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
